In [1]:
print("hi")

hi

In [2]:
for i in range(1, 10):
    print(i)

1
2
3
4
5
6
7
8
9

In [3]:
=

SyntaxError: invalid syntax (1763773627.py, line 1)

In [1]:
%pip install pandas

Requirement already satisfied: pandas in /home/pratik/venv/lib/python3.12/site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in /home/pratik/venv/lib/python3.12/site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/pratik/venv/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/pratik/venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

In [3]:
import numpy as np

In [4]:
import matplotlib.pyplot as plt

In [6]:
df = pd.read_csv("flie.csv")

In [7]:
df

   id         name              email    role    status
0   1   Raj Sharma    raj.s@email.com   Admin    Active
1   2  Priya Singh  priya.s@email.com  Editor    Active
2   3   Amit Patel  a.patel@email.com  Viewer  Inactive
3   4   Neha Gupta  n.gupta@email.com  Editor    Active

In [8]:
df.head()

   id         name              email    role    status
0   1   Raj Sharma    raj.s@email.com   Admin    Active
1   2  Priya Singh  priya.s@email.com  Editor    Active
2   3   Amit Patel  a.patel@email.com  Viewer  Inactive
3   4   Neha Gupta  n.gupta@email.com  Editor    Active

In [19]:
cols = ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11"]

In [22]:
df = pd.read_csv("test.csv")

In [23]:
df.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S