In [3]:
#start of feature scaling

In [25]:
import pandas as pd

df = pd.DataFrame({
    "Age":[18,20,25,30,40],
    "Salary":[25000,30000,45000,60000,100000]
})

In [26]:
df

   Age  Salary
0   18   25000
1   20   30000
2   25   45000
3   30   60000
4   40  100000

In [27]:
from sklearn.preprocessing import StandardScaler

In [28]:
df_s = StandardScaler().fit_transform(df)

In [29]:
df_s

array([[-1.09009327, -1.00206399],
       [-0.83658321, -0.81649658],
       [-0.20280805, -0.25979437],
       [ 0.43096711,  0.29690785],
       [ 1.69851742,  1.78144709]])

In [30]:
from sklearn.preprocessing import MinMaxScaler

In [37]:
df_m = MinMaxScaler().fit_transform(df)

In [38]:
df_m

array([[0.        , 0.        ],
       [0.09090909, 0.06666667],
       [0.31818182, 0.26666667],
       [0.54545455, 0.46666667],
       [1.        , 1.        ]])

In [41]:
df = pd.DataFrame({
    "Age":[20,25,30,35,40],
    "Salary":[30000,40000,50000,60000,70000],
    "Experience":[1,2,3,4,5],
    "Country":["India","India","India","India","India"],
    "Purchased":[0,0,1,1,1]
})

In [42]:
df

   Age  Salary  Experience Country  Purchased
0   20   30000           1   India          0
1   25   40000           2   India          0
2   30   50000           3   India          1
3   35   60000           4   India          1
4   40   70000           5   India          1

In [45]:
#using the corr method findding which features are best to select based on corr
df.corr(numeric_only=1)

                 Age    Salary  Experience  Purchased
Age         1.000000  1.000000    1.000000   0.866025
Salary      1.000000  1.000000    1.000000   0.866025
Experience  1.000000  1.000000    1.000000   0.866025
Purchased   0.866025  0.866025    0.866025   1.000000

In [60]:
#using the selectKbest method
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif

In [61]:
selector = SelectKBest(score_func=f_classif, k=2)

In [62]:
X = df.drop(["Purchased", "Country"], axis=1)

In [63]:
y = df['Purchased']

In [64]:
selector.fit_transform(X, y)

array([[30000,     1],
       [40000,     2],
       [50000,     3],
       [60000,     4],
       [70000,     5]])